# fly.toml app configuration file generated for chatbotquitutesgranja on 2025-10-20T10:08:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatbotquitutesgranja'
primary_region = 'gru'

[build]

[env]
  # Variáveis de ambiente não-sensíveis (se houver)

# Desabilitar auto start/stop já que é um bot que precisa rodar 24/7
[experimental]
  auto_rollback = true

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
